/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
    colors: {
      purple: "#633CFF",
      purpleHoverColor: "#BEADFF",
      lightPurple: "#EFEBFF",
      darkGrey: "#333",
      gray: "#737373",
      borders: "#D9D9D9",
      lightGray: "#fafafa",
      white: "#FFF",
      red: "#ff3939",
      transparent: "transparent",
      github: "#1A1A1A",
      frontendmentor: "#fff",
      twitter: "#43B7E9",
      linkedin: "#2D68FF",
      youtube: "#EE3939",
      facebook: "#2442AC",
      twitch: "#EE3FC8",
      devto: "#333",
      codewars: "#8A1A50",
      codepen: "#000000",
      freecodecamp: "#302267",
      gitlab: "#EB4925",
      hashnode: "#0330D1",
      stackoverflow: "#EC7100",
    },
    fontFamily: {
      instrumentSansItalic: ["Instrument Sans Italic", "sans-serif"],
      instrumentSans: ["Instrument Sans", "sans-serif"],
    },
    boxShadow: {
      activeSelection: "0px 0px 32px 0px rgba(99, 60, 255, 0.25)",
      black: "0px 0px 32px 0px rgba(0, 0, 0, .1)",
      link: "0px 0px 16px 0px rgba(0, 0, 0, .3)",
      none: "none",
    },
  },
  plugins: [],
};
